let activeTradingPair = 'BTC/USDT';
let activeFormTab = 'limit'; // 'limit' or 'market'
let activeUserTab = 'open-orders'; // 'open-orders', 'order-history', 'funds'

window.renderTrade = function(params) {
    if (params && params.pair) {
        activeTradingPair = decodeURIComponent(params.pair).toUpperCase();
        if (!state.tickers[activeTradingPair]) {
            activeTradingPair = 'BTC/USDT';
        }
    }
    state.activeTradingPair = activeTradingPair;
    
    const baseAsset = activeTradingPair.split('/')[0];
    const quoteAsset = activeTradingPair.split('/')[1] || 'USDT';
    const ticker = state.tickers[activeTradingPair];

    // Select options for trading pairs
    let pairOptionsHTML = '';
    Object.keys(state.tickers).forEach(pair => {
        pairOptionsHTML += `<option value="${pair}" ${pair === activeTradingPair ? 'selected' : ''}>${pair}</option>`;
    });

    return `
        <div class="trade-container">
            <!-- Header Ticker Row -->
            <div class="trade-tickers-header">
                <div class="trade-current-pair">
                    <select id="trade-pair-selector">
                        ${pairOptionsHTML}
                    </select>
                </div>
                <div class="trade-ticker-stat">
                    <span class="label">Price</span>
                    <span class="value value-price ${ticker.change24h >= 0 ? 'text-green' : 'text-red'}" id="trade-header-price">$${ticker.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 4 })}</span>
                </div>
                <div class="trade-ticker-stat">
                    <span class="label">24h Change</span>
                    <span class="value ${ticker.change24h >= 0 ? 'text-green' : 'text-red'}" id="trade-header-change">${ticker.change24h >= 0 ? '+' : ''}${ticker.change24h.toFixed(2)}%</span>
                </div>
                <div class="trade-ticker-stat">
                    <span class="label">24h High</span>
                    <span class="value" id="trade-header-high">$${ticker.high24h.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                </div>
                <div class="trade-ticker-stat">
                    <span class="label">24h Low</span>
                    <span class="value" id="trade-header-low">$${ticker.low24h.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                </div>
                <div class="trade-ticker-stat">
                    <span class="label">24h Volume(${baseAsset})</span>
                    <span class="value" id="trade-header-vol">${ticker.volume24h.toLocaleString('en-US', { maximumFractionDigits: 0 })}</span>
                </div>
            </div>

            <!-- Left Panel: Order Book -->
            <div class="trade-panel">
                <div class="panel-header">
                    <span>Order Book</span>
                    <span>Spot</span>
                </div>
                <div class="orderbook-list">
                    <!-- Asks (Red) -->
                    <div id="ob-asks" style="display: flex; flex-direction: column-reverse; height: 180px; justify-content: flex-end; overflow: hidden;">
                        <!-- Generated by JS -->
                    </div>
                    <!-- Spread Bar -->
                    <div class="ob-spread-row">
                        <div>
                            <span class="ob-spread-price ${ticker.change24h >= 0 ? 'text-green' : 'text-red'}" id="ob-spread-price-val">$${ticker.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 4 })}</span>
                        </div>
                        <div class="ob-spread-val" id="ob-spread-fiat">=$${ticker.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                    </div>
                    <!-- Bids (Green) -->
                    <div id="ob-bids" style="display: flex; flex-direction: column; height: 180px; overflow: hidden;">
                        <!-- Generated by JS -->
                    </div>
                </div>
            </div>

            <!-- Center Panel: Chart & Forms -->
            <div class="trade-center-panel">
                <!-- TradingView Chart -->
                <div class="trade-chart-section">
                    <div class="chart-widget-container" id="tradingview-container">
                        <!-- TV embed loaded dynamically by JS -->
                    </div>
                </div>

                <!-- Forms Area -->
                <div class="trade-forms-section">
                    <div class="trade-forms-tabs">
                        <button class="form-tab-btn ${activeFormTab === 'limit' ? 'active' : ''}" id="tab-trade-limit">Limit</button>
                        <button class="form-tab-btn ${activeFormTab === 'market' ? 'active' : ''}" id="tab-trade-market">Market</button>
                    </div>

                    <div class="trade-forms-grid">
                        <!-- Buy Form -->
                        <div class="trade-form">
                            <div class="form-balance-row">
                                <span>Avbl</span>
                                <span id="buy-avbl-balance">0.00 USDT</span>
                            </div>
                            
                            <div class="trade-field-group" id="buy-price-group">
                                <label for="buy-price">Price</label>
                                <input type="number" id="buy-price" value="${ticker.price.toFixed(2)}" step="0.01">
                                <span>USDT</span>
                            </div>
                            <div class="trade-field-group ${activeFormTab === 'market' ? '' : 'hidden'}" id="buy-market-indicator" style="background-color: var(--bg-hover); padding: 11px 12px; border-radius: var(--border-radius-sm);">
                                <span style="font-size: 13px; font-weight: 600; color: var(--text-secondary);">Market Price</span>
                            </div>

                            <div class="trade-field-group">
                                <label for="buy-amount">Amount</label>
                                <input type="number" id="buy-amount" placeholder="0" step="any">
                                <span>${baseAsset}</span>
                            </div>

                            <div class="slider-group">
                                <button class="slider-btn buy-slider" data-pct="0.25">25%</button>
                                <button class="slider-btn buy-slider" data-pct="0.50">50%</button>
                                <button class="slider-btn buy-slider" data-pct="0.75">75%</button>
                                <button class="slider-btn buy-slider" data-pct="1.00">100%</button>
                            </div>

                            <div class="trade-field-group" id="buy-total-group">
                                <label for="buy-total">Total</label>
                                <input type="number" id="buy-total" placeholder="0" step="any">
                                <span>USDT</span>
                            </div>

                            <button class="btn-trade-execute buy-btn" id="btn-submit-buy">Buy ${baseAsset}</button>
                        </div>

                        <!-- Sell Form -->
                        <div class="trade-form">
                            <div class="form-balance-row">
                                <span>Avbl</span>
                                <span id="sell-avbl-balance">0.00 ${baseAsset}</span>
                            </div>

                            <div class="trade-field-group" id="sell-price-group">
                                <label for="sell-price">Price</label>
                                <input type="number" id="sell-price" value="${ticker.price.toFixed(2)}" step="0.01">
                                <span>USDT</span>
                            </div>
                            <div class="trade-field-group ${activeFormTab === 'market' ? '' : 'hidden'}" id="sell-market-indicator" style="background-color: var(--bg-hover); padding: 11px 12px; border-radius: var(--border-radius-sm);">
                                <span style="font-size: 13px; font-weight: 600; color: var(--text-secondary);">Market Price</span>
                            </div>

                            <div class="trade-field-group">
                                <label for="sell-amount">Amount</label>
                                <input type="number" id="sell-amount" placeholder="0" step="any">
                                <span>${baseAsset}</span>
                            </div>

                            <div class="slider-group">
                                <button class="slider-btn sell-slider" data-pct="0.25">25%</button>
                                <button class="slider-btn sell-slider" data-pct="0.50">50%</button>
                                <button class="slider-btn sell-slider" data-pct="0.75">75%</button>
                                <button class="slider-btn sell-slider" data-pct="1.00">100%</button>
                            </div>

                            <div class="trade-field-group" id="sell-total-group">
                                <label for="sell-total">Total</label>
                                <input type="number" id="sell-total" placeholder="0" step="any">
                                <span>USDT</span>
                            </div>

                            <button class="btn-trade-execute sell-btn" id="btn-submit-sell">Sell ${baseAsset}</button>
                        </div>
                    </div>
                </div>

                <!-- User Orders Dashboard -->
                <div class="trade-user-panel">
                    <div class="user-panel-tabs">
                        <button class="panel-tab-btn ${activeUserTab === 'open-orders' ? 'active' : ''}" data-tab="open-orders">Open Orders (<span id="open-orders-count">0</span>)</button>
                        <button class="panel-tab-btn ${activeUserTab === 'order-history' ? 'active' : ''}" data-tab="order-history">Order History</button>
                        <button class="panel-tab-btn ${activeUserTab === 'funds' ? 'active' : ''}" data-tab="funds">Funds</button>
                    </div>
                    <div class="user-panel-content" id="trade-user-content">
                        <!-- Loaded dynamically -->
                    </div>
                </div>
            </div>

            <!-- Right Panel: Market Trade Feed -->
            <div class="trade-panel right">
                <div class="panel-header">
                    <span>Market History</span>
                    <span>Real-time</span>
                </div>
                <div class="market-trades-list" id="trade-history-feed">
                    <!-- Trades list loaded by JS -->
                </div>
            </div>
        </div>
    `;
}

window.initTrade = function(params) {
    activeFormTab = 'limit';
    activeUserTab = 'open-orders';
    
    // Set up TradingView Chart
    initTradingViewChart();

    // Wire dropdown pair selector
    const pairSelector = document.getElementById('trade-pair-selector');
    if (pairSelector) {
        pairSelector.addEventListener('change', (e) => {
            window.location.hash = `#trade?pair=${encodeURIComponent(e.target.value)}`;
        });
    }

    // Tab buttons for forms (Limit / Market)
    const limitTab = document.getElementById('tab-trade-limit');
    const marketTab = document.getElementById('tab-trade-market');
    
    if (limitTab && marketTab) {
        limitTab.addEventListener('click', () => {
            activeFormTab = 'limit';
            limitTab.classList.add('active');
            marketTab.classList.remove('active');
            
            document.getElementById('buy-price-group').classList.remove('hidden');
            document.getElementById('sell-price-group').classList.remove('hidden');
            document.getElementById('buy-market-indicator').classList.add('hidden');
            document.getElementById('sell-market-indicator').classList.add('hidden');
            clearFormAmounts();
        });
        marketTab.addEventListener('click', () => {
            activeFormTab = 'market';
            marketTab.classList.add('active');
            limitTab.classList.remove('active');
            
            document.getElementById('buy-price-group').classList.add('hidden');
            document.getElementById('sell-price-group').classList.add('hidden');
            document.getElementById('buy-market-indicator').classList.remove('hidden');
            document.getElementById('sell-market-indicator').classList.remove('hidden');
            clearFormAmounts();
        });
    }

    // Set up initial form validation listeners and math converters
    setupTradeFormMath();

    // Setup bottom panels (open orders, history, funds)
    document.querySelectorAll('.panel-tab-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.panel-tab-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            activeUserTab = btn.dataset.tab;
            renderUserPanelContent();
        });
    });

    // Populate balances
    updateTradeAvblBalances();

    // Generate Initial Order Book
    generateOrderBook();

    // Generate Mock Feed
    generateTradeFeed();

    // Draw user dashboards
    renderUserPanelContent();

    // Wire custom tickers updates
    window.addEventListener('tickerUpdate', handleLiveTickersTrade);
}

// Draw TradingView widget inside viewport
function initTradingViewChart() {
    const container = document.getElementById('tradingview-container');
    if (!container) return;

    const baseSymbol = activeTradingPair.split('/')[0];
    
    // Clear out container first
    container.innerHTML = `<div id="tradingview_chart" style="width: 100%; height: 100%;"></div>`;

    if (window.TradingView) {
        try {
            new TradingView.widget({
                "width": "100%",
                "height": "100%",
                "symbol": `BINANCE:${baseSymbol}USDT`,
                "interval": "30",
                "timezone": "Etc/UTC",
                "theme": state.theme === "dark" ? "dark" : "light",
                "style": "1",
                "locale": "en",
                "toolbar_bg": "#181a20",
                "enable_publishing": false,
                "hide_side_toolbar": false,
                "allow_symbol_change": false,
                "container_id": "tradingview_chart"
            });
        } catch (e) {
            renderChartFallback();
        }
    } else {
        renderChartFallback();
    }
}

function renderChartFallback() {
    const chartDiv = document.getElementById('tradingview_chart');
    if (chartDiv) {
        chartDiv.outerHTML = `
            <div class="chart-fallback">
                <i data-lucide="bar-chart-2"></i>
                <p>TradingView Interactive Chart Offline</p>
                <span style="font-size: 11px; margin-top: 4px; color: var(--text-muted);">(Requires internet connection to load chart scripts)</span>
            </div>
        `;
        if (window.lucide) lucide.createIcons();
    }
}

// Generate Static / Dynamic mock Order Book
let baseBids = [];
let baseAsks = [];
function generateOrderBook() {
    const ticker = state.tickers[activeTradingPair];
    const price = ticker.price;
    
    baseBids = [];
    baseAsks = [];

    // Generate 8 asks slightly above current price
    for (let i = 1; i <= 8; i++) {
        const askPrice = price * (1 + (i * 0.0003));
        const amount = Math.random() * 2.5 + 0.01;
        baseAsks.push({ price: askPrice, amount: amount });
    }

    // Generate 8 bids slightly below current price
    for (let i = 1; i <= 8; i++) {
        const bidPrice = price * (1 - (i * 0.0003));
        const amount = Math.random() * 2.5 + 0.01;
        baseBids.push({ price: bidPrice, amount: amount });
    }

    renderOrderBookDOM();
}

function renderOrderBookDOM() {
    const asksContainer = document.getElementById('ob-asks');
    const bidsContainer = document.getElementById('ob-bids');
    if (!asksContainer || !bidsContainer) return;

    // Red Asks Rows
    let asksHTML = '';
    let cumulativeAskTotal = 0;
    
    // Accumulate for depth shading
    const maxAskTotal = baseAsks.reduce((sum, item) => sum + item.amount, 0);
    
    baseAsks.forEach(ask => {
        cumulativeAskTotal += ask.amount;
        const total = ask.price * ask.amount;
        const percentage = Math.min((cumulativeAskTotal / maxAskTotal) * 100, 100);
        
        asksHTML += `
            <div class="ob-row" onclick="fillFormPrice(${ask.price})">
                <div class="depth-bar bg-red" style="width: ${percentage}%;"></div>
                <span class="price-col text-red">${ask.price.toFixed(2)}</span>
                <span>${ask.amount.toFixed(4)}</span>
                <span>${total.toFixed(2)}</span>
            </div>
        `;
    });
    asksContainer.innerHTML = asksHTML;

    // Green Bids Rows
    let bidsHTML = '';
    let cumulativeBidTotal = 0;
    const maxBidTotal = baseBids.reduce((sum, item) => sum + item.amount, 0);

    baseBids.forEach(bid => {
        cumulativeBidTotal += bid.amount;
        const total = bid.price * bid.amount;
        const percentage = Math.min((cumulativeBidTotal / maxBidTotal) * 100, 100);
        
        bidsHTML += `
            <div class="ob-row" onclick="fillFormPrice(${bid.price})">
                <div class="depth-bar bg-green" style="width: ${percentage}%;"></div>
                <span class="price-col text-green">${bid.price.toFixed(2)}</span>
                <span>${bid.amount.toFixed(4)}</span>
                <span>${total.toFixed(2)}</span>
            </div>
        `;
    });
    bidsContainer.innerHTML = bidsHTML;
}

window.fillFormPrice = function(price) {
    const buyPriceInput = document.getElementById('buy-price');
    const sellPriceInput = document.getElementById('sell-price');
    
    if (buyPriceInput) buyPriceInput.value = price.toFixed(2);
    if (sellPriceInput) sellPriceInput.value = price.toFixed(2);
    
    // Update math calculations
    const buyAmt = document.getElementById('buy-amount');
    const buyTot = document.getElementById('buy-total');
    if (buyAmt && buyAmt.value) {
        buyTot.value = (parseFloat(buyAmt.value) * price).toFixed(2);
    }
    const sellAmt = document.getElementById('sell-amount');
    const sellTot = document.getElementById('sell-total');
    if (sellAmt && sellAmt.value) {
        sellTot.value = (parseFloat(sellAmt.value) * price).toFixed(2);
    }
};

// Generate Mock Trades Feed
let tradesFeed = [];
function generateTradeFeed() {
    const feedContainer = document.getElementById('trade-history-feed');
    if (!feedContainer) return;

    const ticker = state.tickers[activeTradingPair];
    const price = ticker.price;
    tradesFeed = [];

    // Create 15 starter trades
    for (let i = 0; i < 20; i++) {
        const pctOffset = (Math.random() - 0.5) * 0.001;
        const tradePrice = price * (1 + pctOffset);
        const amount = Math.random() * 1.8 + 0.002;
        const side = Math.random() > 0.48 ? 'Buy' : 'Sell';
        
        // Random time offset
        const d = new Date();
        d.setSeconds(d.getSeconds() - (i * 3));
        const timeStr = d.toTimeString().split(' ')[0];

        tradesFeed.push({
            price: tradePrice,
            amount: amount,
            side: side,
            time: timeStr
        });
    }

    renderTradeFeedDOM();
}

function renderTradeFeedDOM() {
    const feedContainer = document.getElementById('trade-history-feed');
    if (!feedContainer) return;

    let html = '';
    tradesFeed.forEach(t => {
        html += `
            <div class="mt-row">
                <span class="price-col ${t.side === 'Buy' ? 'text-green' : 'text-red'}">${t.price.toFixed(2)}</span>
                <span>${t.amount.toFixed(5)}</span>
                <span class="time-col">${t.time}</span>
            </div>
        `;
    });
    feedContainer.innerHTML = html;
}

// Helper to clear inputs
function clearFormAmounts() {
    document.getElementById('buy-amount').value = '';
    document.getElementById('buy-total').value = '';
    document.getElementById('sell-amount').value = '';
    document.getElementById('sell-total').value = '';
    
    document.querySelectorAll('.slider-btn').forEach(btn => btn.classList.remove('active'));
}

// Auto calculation when user types amounts/price
function setupTradeFormMath() {
    const buyPrice = document.getElementById('buy-price');
    const buyAmount = document.getElementById('buy-amount');
    const buyTotal = document.getElementById('buy-total');
    
    const sellPrice = document.getElementById('sell-price');
    const sellAmount = document.getElementById('sell-amount');
    const sellTotal = document.getElementById('sell-total');

    // Auto-calculates Total on Amount or Price changes
    function calcBuyTotal() {
        const price = activeFormTab === 'limit' ? (parseFloat(buyPrice.value) || 0) : state.tickers[activeTradingPair].price;
        const amount = parseFloat(buyAmount.value) || 0;
        buyTotal.value = (price * amount).toFixed(2);
    }
    buyAmount.addEventListener('input', calcBuyTotal);
    buyPrice.addEventListener('input', calcBuyTotal);

    // Auto-calculates Amount on Total changes
    buyTotal.addEventListener('input', () => {
        const price = activeFormTab === 'limit' ? (parseFloat(buyPrice.value) || 0) : state.tickers[activeTradingPair].price;
        const total = parseFloat(buyTotal.value) || 0;
        if (price > 0) {
            buyAmount.value = (total / price).toFixed(6);
        }
    });

    function calcSellTotal() {
        const price = activeFormTab === 'limit' ? (parseFloat(sellPrice.value) || 0) : state.tickers[activeTradingPair].price;
        const amount = parseFloat(sellAmount.value) || 0;
        sellTotal.value = (price * amount).toFixed(2);
    }
    sellAmount.addEventListener('input', calcSellTotal);
    sellPrice.addEventListener('input', calcSellTotal);

    sellTotal.addEventListener('input', () => {
        const price = activeFormTab === 'limit' ? (parseFloat(sellPrice.value) || 0) : state.tickers[activeTradingPair].price;
        const total = parseFloat(sellTotal.value) || 0;
        if (price > 0) {
            sellAmount.value = (total / price).toFixed(6);
        }
    });

    // Slider percent handlers
    document.querySelectorAll('.buy-slider').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.buy-slider').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            const pct = parseFloat(btn.dataset.pct);
            const avbl = state.user.balances.USDT;
            const price = activeFormTab === 'limit' ? (parseFloat(buyPrice.value) || state.tickers[activeTradingPair].price) : state.tickers[activeTradingPair].price;
            
            if (price > 0) {
                const total = avbl * pct;
                buyTotal.value = total.toFixed(2);
                buyAmount.value = (total / price).toFixed(6);
            }
        });
    });

    document.querySelectorAll('.sell-slider').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.sell-slider').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            const pct = parseFloat(btn.dataset.pct);
            const baseSymbol = activeTradingPair.split('/')[0];
            const avbl = state.user.balances[baseSymbol] || 0;
            const price = activeFormTab === 'limit' ? (parseFloat(sellPrice.value) || state.tickers[activeTradingPair].price) : state.tickers[activeTradingPair].price;
            
            const amt = avbl * pct;
            sellAmount.value = amt.toFixed(6);
            sellTotal.value = (amt * price).toFixed(2);
        });
    });

    // Submissions
    document.getElementById('btn-submit-buy').addEventListener('click', processBuyOrder);
    document.getElementById('btn-submit-sell').addEventListener('click', processSellOrder);
}

function updateTradeAvblBalances() {
    const buyBalSpan = document.getElementById('buy-avbl-balance');
    const sellBalSpan = document.getElementById('sell-avbl-balance');
    const baseSymbol = activeTradingPair.split('/')[0];

    if (!state.user.isLoggedIn) {
        if (buyBalSpan) buyBalSpan.textContent = '0.00 USDT';
        if (sellBalSpan) sellBalSpan.textContent = `0.00 ${baseSymbol}`;
        return;
    }

    if (buyBalSpan) buyBalSpan.textContent = `${state.user.balances.USDT.toLocaleString('en-US', { minimumFractionDigits: 2 })} USDT`;
    if (sellBalSpan) {
        const bal = state.user.balances[baseSymbol] || 0;
        sellBalSpan.textContent = `${bal.toLocaleString('en-US', { minimumFractionDigits: 4 })} ${baseSymbol}`;
    }
}

// Handle Order Submissions
function processBuyOrder() {
    if (!state.user.isLoggedIn) {
        alert('Please login to place trades.');
        window.location.hash = '#auth';
        return;
    }

    const priceInput = document.getElementById('buy-price');
    const amountInput = document.getElementById('buy-amount');
    const totalInput = document.getElementById('buy-total');
    
    const price = activeFormTab === 'limit' ? parseFloat(priceInput.value) : state.tickers[activeTradingPair].price;
    const amount = parseFloat(amountInput.value) || 0;
    const total = parseFloat(totalInput.value) || 0;

    if (amount <= 0 || total <= 0) {
        alert('Please enter valid Amount/Total values.');
        return;
    }

    if (state.user.balances.USDT < total) {
        alert('Insufficient USDT balance.');
        return;
    }

    // Deduct balance
    state.user.balances.USDT -= total;
    
    const baseSymbol = activeTradingPair.split('/')[0];
    
    if (activeFormTab === 'limit') {
        // Place Limit Order
        state.openOrders.unshift({
            id: 'ord-' + Date.now().toString().slice(-6),
            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
            pair: activeTradingPair,
            type: 'Limit',
            side: 'Buy',
            price: price,
            amount: amount,
            total: total
        });
        alert(`Limit Buy Order Placed for ${amount.toFixed(5)} ${baseSymbol} at $${price.toFixed(2)}.`);
    } else {
        // Instant Market Fill
        state.user.balances[baseSymbol] = (state.user.balances[baseSymbol] || 0) + amount;
        state.orderHistory.unshift({
            id: 'ord-' + Date.now().toString().slice(-6),
            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
            pair: activeTradingPair,
            type: 'Market',
            side: 'Buy',
            price: price,
            amount: amount,
            total: total,
            status: 'Filled'
        });
        alert(`Market Order Filled! Bought ${amount.toFixed(5)} ${baseSymbol} at market price.`);
    }

    saveTradeAppState();
    updateTradeAvblBalances();
    renderUserPanelContent();
    clearFormAmounts();
    updateHeaderBalance();
}

function processSellOrder() {
    if (!state.user.isLoggedIn) {
        alert('Please login to place trades.');
        window.location.hash = '#auth';
        return;
    }

    const priceInput = document.getElementById('sell-price');
    const amountInput = document.getElementById('sell-amount');
    const totalInput = document.getElementById('sell-total');
    
    const price = activeFormTab === 'limit' ? parseFloat(priceInput.value) : state.tickers[activeTradingPair].price;
    const amount = parseFloat(amountInput.value) || 0;
    const total = parseFloat(totalInput.value) || 0;

    const baseSymbol = activeTradingPair.split('/')[0];
    const userBaseBalance = state.user.balances[baseSymbol] || 0;

    if (amount <= 0 || total <= 0) {
        alert('Please enter valid Amount/Total values.');
        return;
    }

    if (userBaseBalance < amount) {
        alert(`Insufficient ${baseSymbol} balance.`);
        return;
    }

    // Deduct balance
    state.user.balances[baseSymbol] -= amount;

    if (activeFormTab === 'limit') {
        // Limit Sell
        state.openOrders.unshift({
            id: 'ord-' + Date.now().toString().slice(-6),
            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
            pair: activeTradingPair,
            type: 'Limit',
            side: 'Sell',
            price: price,
            amount: amount,
            total: total
        });
        alert(`Limit Sell Order Placed for ${amount.toFixed(5)} ${baseSymbol} at $${price.toFixed(2)}.`);
    } else {
        // Market Sell Fill
        state.user.balances.USDT += total;
        state.orderHistory.unshift({
            id: 'ord-' + Date.now().toString().slice(-6),
            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
            pair: activeTradingPair,
            type: 'Market',
            side: 'Sell',
            price: price,
            amount: amount,
            total: total,
            status: 'Filled'
        });
        alert(`Market Order Filled! Sold ${amount.toFixed(5)} ${baseSymbol} at market price.`);
    }

    saveTradeAppState();
    updateTradeAvblBalances();
    renderUserPanelContent();
    clearFormAmounts();
    updateHeaderBalance();
}

function saveTradeAppState() {
    localStorage.setItem('binance_clone_state', JSON.stringify({
        user: state.user,
        favorites: state.favorites,
        openOrders: state.openOrders,
        orderHistory: state.orderHistory,
        p2pOrders: state.p2pOrders,
        theme: state.theme
    }));
}

// Render the bottom dashboard tables (Open Orders, Order History, Funds)
function renderUserPanelContent() {
    const container = document.getElementById('trade-user-content');
    const openOrdersCountSpan = document.getElementById('open-orders-count');
    
    if (openOrdersCountSpan) {
        openOrdersCountSpan.textContent = state.openOrders.length;
    }

    if (!container) return;

    if (!state.user.isLoggedIn) {
        container.innerHTML = `
            <div class="empty-state">
                <i data-lucide="lock"></i>
                <p>Please log in to view active orders and trading funds.</p>
            </div>
        `;
        if (window.lucide) lucide.createIcons();
        return;
    }

    if (activeUserTab === 'open-orders') {
        if (state.openOrders.length === 0) {
            container.innerHTML = `
                <div class="empty-state">
                    <i data-lucide="file-text"></i>
                    <p>No open orders</p>
                </div>
            `;
            if (window.lucide) lucide.createIcons();
            return;
        }

        let html = `
            <table class="orders-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Pair</th>
                        <th>Type</th>
                        <th>Side</th>
                        <th>Price</th>
                        <th>Amount</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
        `;

        state.openOrders.forEach(o => {
            html += `
                <tr>
                    <td>${o.time}</td>
                    <td>${o.pair}</td>
                    <td>${o.type}</td>
                    <td class="${o.side === 'Buy' ? 'text-green' : 'text-red'}">${o.side}</td>
                    <td>$${o.price.toFixed(2)}</td>
                    <td>${o.amount.toFixed(5)}</td>
                    <td>$${o.total.toFixed(2)}</td>
                    <td><button class="btn-cancel-order" onclick="cancelUserOrder('${o.id}')">Cancel</button></td>
                </tr>
            `;
        });
        html += `</tbody></table>`;
        container.innerHTML = html;
        
    } else if (activeUserTab === 'order-history') {
        if (state.orderHistory.length === 0) {
            container.innerHTML = `
                <div class="empty-state">
                    <i data-lucide="history"></i>
                    <p>No order history</p>
                </div>
            `;
            if (window.lucide) lucide.createIcons();
            return;
        }

        let html = `
            <table class="orders-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Pair</th>
                        <th>Type</th>
                        <th>Side</th>
                        <th>Price</th>
                        <th>Amount</th>
                        <th>Total</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
        `;

        state.orderHistory.forEach(o => {
            html += `
                <tr>
                    <td>${o.time}</td>
                    <td>${o.pair}</td>
                    <td>${o.type}</td>
                    <td class="${o.side === 'Buy' ? 'text-green' : 'text-red'}">${o.side}</td>
                    <td>$${o.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 4 })}</td>
                    <td>${o.amount.toFixed(5)}</td>
                    <td>$${o.total.toFixed(2)}</td>
                    <td><span class="text-green">${o.status || 'Filled'}</span></td>
                </tr>
            `;
        });
        html += `</tbody></table>`;
        container.innerHTML = html;

    } else if (activeUserTab === 'funds') {
        let html = `
            <table class="orders-table">
                <thead>
                    <tr>
                        <th>Asset</th>
                        <th>Total Balance</th>
                        <th>Available Balance</th>
                        <th>Estimated Value (USDT)</th>
                    </tr>
                </thead>
                <tbody>
        `;

        for (const [symbol, amount] of Object.entries(state.user.balances)) {
            let estValue = amount;
            if (symbol !== 'USDT') {
                const pair = `${symbol}/USDT`;
                if (state.tickers[pair]) {
                    estValue = amount * state.tickers[pair].price;
                } else {
                    estValue = 0;
                }
            }

            html += `
                <tr>
                    <td><strong>${symbol}</strong></td>
                    <td>${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 })}</td>
                    <td>${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 })}</td>
                    <td>$${estValue.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
            `;
        }
        html += `</tbody></table>`;
        container.innerHTML = html;
    }
}

// Global Order Cancel handler
window.cancelUserOrder = function(orderId) {
    const index = state.openOrders.findIndex(o => o.id === orderId);
    if (index > -1) {
        const order = state.openOrders[index];
        // Refund
        if (order.side === 'Buy') {
            state.user.balances.USDT += order.total;
        } else {
            const baseSymbol = order.pair.split('/')[0];
            state.user.balances[baseSymbol] += order.amount;
        }

        // Add to history as Cancelled
        state.orderHistory.unshift({
            id: order.id,
            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
            pair: order.pair,
            type: order.type,
            side: order.side,
            price: order.price,
            amount: order.amount,
            total: order.total,
            status: 'Cancelled'
        });

        state.openOrders.splice(index, 1);
        alert('Order Cancelled successfully. Funds refunded.');
        
        saveTradeAppState();
        updateTradeAvblBalances();
        renderUserPanelContent();
        updateHeaderBalance();
    }
};

// Handle live simulated prices on the trading dashboard
window.updateTradeLive = function(changes) {
    changes.forEach(change => {
        if (change.pair === activeTradingPair) {
            // Update Header Stats
            const pLabel = document.getElementById('trade-header-price');
            const cLabel = document.getElementById('trade-header-change');
            const hLabel = document.getElementById('trade-header-high');
            const lLabel = document.getElementById('trade-header-low');
            
            const isPositive = change.change24h >= 0;
            const sign = isPositive ? '+' : '';
            const textClass = isPositive ? 'text-green' : 'text-red';
            
            if (pLabel) {
                pLabel.textContent = `$${change.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 4 })}`;
                pLabel.className = `value value-price ${textClass}`;
                
                // Glow flash on change
                pLabel.classList.remove('flash-green-anim', 'flash-red-anim');
                void pLabel.offsetWidth;
                pLabel.classList.add(change.isUp ? 'flash-green-anim' : 'flash-red-anim');
            }
            if (cLabel) {
                cLabel.textContent = `${sign}${change.change24h.toFixed(2)}%`;
                cLabel.className = `value ${textClass}`;
            }

            const ticker = state.tickers[activeTradingPair];
            if (hLabel) hLabel.textContent = `$${ticker.high24h.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
            if (lLabel) lLabel.textContent = `$${ticker.low24h.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

            // Update Order Book spread
            const spreadPrice = document.getElementById('ob-spread-price-val');
            const spreadFiat = document.getElementById('ob-spread-fiat');
            if (spreadPrice) {
                spreadPrice.textContent = `$${change.price.toFixed(2)}`;
                spreadPrice.className = `ob-spread-price ${textClass}`;
            }
            if (spreadFiat) {
                spreadFiat.textContent = `=$${change.price.toFixed(2)}`;
            }

            // Adjust order book limits dynamic updates
            // Slighly adjust bids / asks
            baseAsks.forEach((ask, i) => {
                ask.price = change.price * (1 + ((i+1) * 0.0003));
            });
            baseBids.forEach((bid, i) => {
                bid.price = change.price * (1 - ((i+1) * 0.0003));
            });
            renderOrderBookDOM();

            // Inject random fills to trade history feed
            if (Math.random() > 0.4) {
                const amount = Math.random() * 0.9 + 0.001;
                const side = Math.random() > 0.5 ? 'Buy' : 'Sell';
                const timeStr = new Date().toTimeString().split(' ')[0];

                tradesFeed.unshift({
                    price: change.price,
                    amount: amount,
                    side: side,
                    time: timeStr
                });
                if (tradesFeed.length > 30) tradesFeed.pop();
                renderTradeFeedDOM();
            }

            // If user tab is Funds, update values
            if (activeUserTab === 'funds') {
                renderUserPanelContent();
            }

            // Check if open orders can be simulated fill (for demo purposes)
            // Match price logic: if buy order price >= current price, fill it!
            // If sell order price <= current price, fill it!
            let orderFilled = false;
            for (let i = state.openOrders.length - 1; i >= 0; i--) {
                const order = state.openOrders[i];
                if (order.pair === activeTradingPair) {
                    if ((order.side === 'Buy' && order.price >= change.price) || 
                        (order.side === 'Sell' && order.price <= change.price)) {
                        
                        // Fill order
                        if (order.side === 'Buy') {
                            const baseSymbol = order.pair.split('/')[0];
                            state.user.balances[baseSymbol] = (state.user.balances[baseSymbol] || 0) + order.amount;
                        } else {
                            state.user.balances.USDT += order.total;
                        }

                        // Add to history
                        state.orderHistory.unshift({
                            id: order.id,
                            time: new Date().toISOString().replace('T', ' ').slice(0, 19),
                            pair: order.pair,
                            type: order.type,
                            side: order.side,
                            price: order.price,
                            amount: order.amount,
                            total: order.total,
                            status: 'Filled'
                        });

                        state.openOrders.splice(i, 1);
                        orderFilled = true;
                    }
                }
            }

            if (orderFilled) {
                saveTradeAppState();
                updateTradeAvblBalances();
                renderUserPanelContent();
                updateHeaderBalance();
            }
        }
    });
}

// Unhook previous windows listener to avoid duplication
const prevTradeTickerHandler = window.binanceTradeTickerHandler;
if (prevTradeTickerHandler) {
    window.removeEventListener('tickerUpdate', prevTradeTickerHandler);
}
function handleLiveTickersTrade(e) {
    window.updateTradeLive(e.detail);
}
window.binanceTradeTickerHandler = handleLiveTickersTrade;
